### ISSUE TITLE
Add search feature to Netbird documentation

### ISSUE THREAD

**Issue by luzfcb** [netbirdio/docs#42]
I discovered Netbird a few weeks ago, and realized that the lack of a search feature in the documentation can make things more difficult than it should be.
The framework that is used for documentation indicates some options: https://docusaurus.io/docs/search

**Comment by pascal-fischer** [comment]
Hi @luzfcb, the redesign of the docs is done. If you check [docs.netbird.io](https://docs.netbird.io) you find a searchbar that will check Docs and API space.
